<?php
define('TITLE', 'Term Of Use'); 
// define('PAGE', 'About');
?>
<!-- Start Head Area -->
<?php include('winclude/head.php'); ?>

<!-- Start Header Area -->
<?php include('winclude/header.php'); ?>

<!-- Start Banner -->
<?php include('winclude/banner.php'); ?>

<!--================Single Product Area =================-->
<section class="banner organic-breadcrumb" style="background-image: url(../img/all.jpg)">
	<div class="container">
		<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
			<div class="col-first">
				<h1>Term Of Use</h1>
			</div>
		</div>
	</div>
</section>
<div class="container-fluid mt-5 mb-5">
	<h1 class="font-size-bold ml-4">Term Of Use</h1>
	<div class="container mt-5">
		<p style="font-size: 20px">Welcome to the <b>BookCart</b>. <b>BookCart</b> Seller Services Private Limited provides this site to you subject to the following conditions. By visiting the <b>BookCart</b> site (the “Site”), you accept these conditions. Please read them carefully. In addition, when you use any current or future <b>BookCart</b> service or business, you also will be subject to the guidelines, terms and agreements applicable to such service or business.</p>

	
		<p style="font-size: 20px">These ‘Conditions of Use’ constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

		<h3>Privacy</h3><br>
		<p style="font-size: 20px">Please review our Privacy Notice, which also governs your visit to this Site, to understand our practices.</p>

		<h5>Electronic Communication</h5><br>
		<p style="font-size: 20px">When you visit the Site or send e-mails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this Site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>

		<h5>Applicable Law</h5><br>
		<p style="font-size: 20px">By visiting this Site, you agree that the laws of India will govern these Terms of Use and any dispute of any sort that might arise between you and Amazon or its affiliates</p>
	</div>
</div>


<!-- Start footer Area -->
<?php include('winclude/footer.php'); ?>